ALTER TABLE ldap_config 
ALTER COLUMN "host" TYPE VARCHAR(128),
ALTER COLUMN "host" DROP NOT NULL,
ALTER COLUMN "host" SET DEFAULT '127.0.0.1',

ALTER COLUMN "port" TYPE DECIMAL(5,0),
ALTER COLUMN "port" DROP NOT NULL,
ALTER COLUMN "port" SET DEFAULT 389 ,

ALTER COLUMN "encryption" TYPE VARCHAR(24) ,
ALTER COLUMN "encryption" DROP NOT NULL,
ALTER COLUMN "encryption" SET DEFAULT 'NONE' ,

ALTER COLUMN "auth" TYPE VARCHAR(24) ,
ALTER COLUMN "auth" DROP NOT NULL,
ALTER COLUMN "auth" SET DEFAULT 'SIMPLE' ,

ALTER COLUMN "admin_bind_dn" TYPE VARCHAR(24),
ALTER COLUMN "admin_bind_dn" DROP NOT NULL,
ALTER COLUMN "admin_bind_dn" SET DEFAULT '',

ALTER COLUMN "server_type" TYPE VARCHAR(24),
ALTER COLUMN "server_type" DROP NOT NULL,
ALTER COLUMN "server_type" SET DEFAULT '' ,

ALTER COLUMN "root_dse" TYPE VARCHAR(24),
ALTER COLUMN "root_dse" DROP NOT NULL,
ALTER COLUMN "root_dse" SET DEFAULT '',

ALTER COLUMN "use_as_auth" TYPE DECIMAL(1,0),
ALTER COLUMN "use_as_auth" DROP NOT NULL,
ALTER COLUMN "use_as_auth" SET DEFAULT 0 ;
